### PR TITLE
undefined response in NetworkError

### PR DESCRIPTION
**Pull request by JoviDeCroock**
Fixes: https://github.com/apollographql/apollo-link/issues/855

This or we add that for a network error the response is undefined in the docs.

### CODE REVIEW

**Comment by Pau1fitz** [comment]
any idea when this will be merged?

**Comment by bregenspan** [comment]
@JoviDeCroock was this closed because it was determined that this is correct behavior, or that it should be fixed differently?

**Comment by JoviDeCroock** [comment]
Accident but I’ve kinda lost hope in merging it

**Comment by avilaj** [comment]
any news in this pr?

**Comment by yifengd** [comment]
What's the status on this? As of now there is still no way to pass GraphQL errors onto the UI in the presence of a non-200 network code.

**Pull request closed without merging**
