### PR TITLE
Persisted queries link

### PR DESCRIPTION
**Pull request by Poincare**
Implements an Apollo Link that provides persisted query support. Still requires integration into the the transport to send the "id" over instead of the query.

TODO:

- [ ] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests
- [ ] Rebase your changes on master so that they can be merged easily
- [ ] Make sure all tests and linter rules pass
- [ ] Update CHANGELOG.md with your change
- [ ] Add your name and email to the AUTHORS file (optional)
- [ ] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

**Comment by jthegedus** [comment]
Might I suggest renaming from `apollo-link-persist` to something like `apollo-link-persisted-queries` as the term *persist* is usually used with respect to offline persistence and rehydration.

**Comment by hlehmann** [comment]
any update on this ?

**Comment by sepehr500** [comment]
Is this still being worked? So you need help to finish?

**Comment by sepehr500** [comment]
This is the only thing keeping my team from moving to 2.0 right now ☹️

**Comment by stubailo** [comment]
Have you taken a look at this? https://github.com/apollographql/apollo-link-persisted-queries

**Comment by stubailo** [comment]
Sorry, shouldn't have closed without a comment.

**Comment by sepehr500** [comment]
Thanks. I will take a look!

**Pull request closed without merging**
