### PR TITLE
Fix zen-observable typescript import

### PR DESCRIPTION
**Pull request by dobesv**
Because zen observable uses the `export = Observable`, it should be imported using the form  `import Observable = require('zen-observable');`.

See https://www.typescriptlang.org/docs/handbook/modules.html under the heading "export = and import = require()":

> When exporting a module using `export =`, TypeScript-specific `import module = require("module")` must be used to import the module.

This error occurs if your tsconfig has 

```
    "esModuleInterop": true,
```

Setting that option to false prevents the error.

### CODE REVIEW

**Comment by dobesv** [comment]
See also https://github.com/apollographql/apollo-link/issues/558

**Comment by dobesv** [comment]
See also https://github.com/apollographql/apollo-link/issues/248

**Comment by dobesv** [comment]
See also https://github.com/apollographql/apollo-link/pull/380 as a possible alternative fix.

**Comment by dobesv** [comment]
See also https://github.com/apollographql/apollo-link/pull/515

**Comment by dobesv** [comment]
See also https://github.com/apollographql/apollo-link/issues/511

**Comment by THoisington** [comment]
I'm not sure if it is appropriate to comment here, but I have a suspicion that this fix could solve an error that has haunted me for the last three days: 

`ERROR in [at-loader] ./node_modules/@types/zen-observable/index.d.ts:8:9 
    TS2687: All declarations of 'observable' must have identical modifiers.`

Really hope this PR can be merged.

**Comment by dobesv** [comment]
It seems like recent changes to master have probably made this PR obsolete.

**Comment by nicky-lenaers** [comment]
Same issue as @THoisington , still present in 1.2.2

**Comment by dobesv** [comment]
@nicky-lenaers You should probably comment on one of the related issues.  This PR would have to be redone since the code it was based on has changed in a significant way.

**Comment by THoisington** [comment]
@nicky-lenaers There is also a [PR in zen-observable](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26239#issuecomment-395925181). For me it was specifically @types/node adding readonly and @types/zen-observable was missing it. Seems like things can really get messy with @types!

**Pull request closed without merging**
