### PR TITLE
Update to new design

### PR DESCRIPTION
**Pull request by unicodeveloper**
TODO:

- [ ] Make sure all of new logic is covered by tests and passes linting
- [ ] Update CHANGELOG.md with your change

**Pull Request Labels**

- [ ] feature
- [ ] blocking
- [ ] docs

### CODE REVIEW

**Comment by abernix** [comment]
This would have happened automatically, but it was blocked on https://github.com/apollographql/apollo-link/pull/583.  In fact, most dependency updates for this repository are blocked on that PR.

**Comment by abernix** [comment]
@evans can we get https://github.com/apollographql/apollo-link/pull/583 merged?

> Important: Renovate will wait until you have merged this Pin request before creating PRs for any upgrades. If you do not wish to pin anything, please update your config accordingly instead of leaving this PR open.

**Comment by unicodeveloper** [comment]
Oh wow @abernix. Thanks for the info

**Comment by abernix** [comment]
@unicodeveloper Thanks for catching it!

**Pull request merged**
