### PR TITLE
@apollo/client integration

### PR DESCRIPTION
**Pull request by hwillson**
Core Apollo Link functionality is being merged into Apollo Client 3. This PR removes the functionality that is going to be part of Apollo Client 3, and updates the remaining packages to include the common functionality they need from `@apollo/client`.

Related:

- https://github.com/apollographql/apollo-client/pull/5116
- https://github.com/apollographql/react-apollo/pull/3536

### CODE REVIEW

**Comment by hwillson** [comment]
Note - tests here will fail until `@apollo/client@3.0.0-alpha.7` is published.

**Comment by kamilkisiela** [comment]
Could we merge apollographql/apollo-client#5541 and use `@apollo/client/common`? Otherwise `apollo-link` and every `apollo-link-*` package will break UI integrations other than React.

**Comment by hwillson** [comment]
The following `beta` Links are now published and ready for testing:

 - apollo-link-batch-http@2.0.0-beta.0
 - apollo-link-batch@2.0.0-beta.0
 - apollo-link-context@2.0.0-beta.0
 - apollo-link-error@2.0.0-beta.0
 - apollo-link-retry@3.0.0-beta.0
 - apollo-link-schema@2.0.0-beta.0
 - apollo-link-ws@2.0.0-beta.0
 - zen-observable-ts@1.0.0-beta.0

These have a dependency on `@apollo/client@beta`. Note that the docs will continue to fail here until we remove the Netlify job completely (which will happen when `@apollo/client` is launched).

**Comment by TamerShlash** [comment]
Hello,

Since the new client package moved from `apollo-client` to `@apollo/client` (which is a lot nicer and cleaner), I'm wondering if the link packages will follow the same convention.

It will be much nicer if the names changed to e.g `@apollo/error-link`, `@apollo/retry-link`.... etc, and will make much more sense when looking at `package.json` or `import`ing from the packages.

**Comment by vvakame** [comment]
@hwillson could you publish with `@apollo/client` RC version?

**Comment by hwillson** [comment]
We've decided to move the rest of the links in this repo over to the Apollo Client repo (details: https://github.com/apollographql/apollo-client/pull/6577).

**Pull request closed without merging**
