### PR TITLE
Deprecate apollo-link-local

### PR DESCRIPTION
**Pull request by imranolas**
...in favor of `apollo-link-schema`. Both packages are practically identical but as `apollo-link-schema` exists under the apollographql org it makes sense to deprecate the former 😢 

TODO:

- [ ] If this PR is a new feature, reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests
- [ ] Rebase your changes on master so that they can be merged easily
- [ ] Make sure all tests and linter rules pass
- [ ] Update CHANGELOG.md with your change
- [ ] Add your name and email to the AUTHORS file (optional)
- [ ] If this was a change that affects the external API, update the docs and post a link to the PR in the discussion

### CODE REVIEW

**Comment by stubailo** [comment]
Oh man! Sorry, I only found out about apollo-link-local yesterday. Is there any difference between the two?

**Comment by stubailo** [comment]
Also I just noticed there aren't docs for the schema link: https://www.apollographql.com/docs/link/

**Comment by zephraph** [comment]
Ahh, sorry @imranolas. Several of us missed the fact your package existed. 

@stubailo, the docs should exist. See https://github.com/apollographql/apollo-link/tree/master/docs/source/links. Schema.md is the link back over to the SchemaLink readme. I'm not sure if I didn't link it correctly or if a special docs deployment needs to happen.

**Comment by stubailo** [comment]
@zephraph I think it needs to be added here: https://github.com/apollographql/apollo-link/blob/master/docs/_config.yml

**Comment by zephraph** [comment]
I see. I'll do a PR for that really quick.

**Comment by zephraph** [comment]
See #319

**Comment by imranolas** [comment]
There's literally no difference. It almost looks like we copy/pasted each others code, haha.

**Comment by stubailo** [comment]
OK, next time we can be more careful to avoid duplicating work! Let's keep writing cool links :]

**Pull request merged**
