### PR TITLE
Add more language about making a custom link

### PR DESCRIPTION
**Pull request by thomassuckow**
**Pull Request Labels**

- [ ] feature
- [ ] blocking
- [x] docs

### CODE REVIEW

**Comment by evans** [comment]
@thomassuckow This is awesome; thank you! If you can sign CLA, we'll be able to get this merged 🎉 

It also looks like we should hav the link readme somewhere accessible on the documentation site. It think somewhere underneath Concepts would be great. You symlink it into the doc folder and then add it to the [configuration file](https://github.com/apollographql/apollo-link/blob/master/docs/_config.yml)

**Comment by abernix** [comment]
@thomassuckow This is fantastic; thank you for taking the time to do this!  If you can, please take a moment to review and sign the Contributor License Agreement.  It just needs your name, address and an "I agree" and is a relatively standard assignment (you'll only need to do it once).  It's important for us to protect the project from copyright prosecution, so we must ask for it!

**Comment by thomassuckow** [comment]
I finally got legal to approve the CLA.

I'll hold off on the symlink, I don't believe it is worded quite right to follow the narrative of the documentation site. But it is still helpful to someone trying to implement an apollo-link and looking up the source code.

**Comment by stubailo** [comment]
Thank you!

**Pull request merged**
