### PR TITLE
Expose generics from graphql ExecutionResult on FetchResult

### PR DESCRIPTION
**Pull request by rosskevin**
TODO:

- [ ] Make sure all of new logic is covered by tests and passes linting
- [x] Update CHANGELOG.md with your change

**Pull Request Labels**

- [ ] feature
- [x] blocking
- [ ] docs

Related to Jul 3 change in `@types/graphql`, update the `FetchResult` generics to strongly type the data.  I added `blocking` because [it prevents strong typing in usage of `apollo-client`](https://github.com/apollographql/apollo-client/issues/2795#issuecomment-424124181).

See: 
- https://github.com/DefinitelyTyped/DefinitelyTyped/commit/deb7d8beaff5d43da749c5bc0f2020cdcaaabb6b#diff-1a92e4f388a3da0eb35da5e193f02172
- https://github.com/apollographql/apollo-client/issues/2795#issuecomment-424124181

### CODE REVIEW

**Comment by ksaldana1** [comment]
Do we have any update on this PR? I ran into this today and was about to throw the same thing up. Thanks for putting this together @rosskevin.

**Comment by mark-buer** [comment]
Is there an ETA for this being merged and released?

**Comment by rosskevin** [comment]
@hwilson LGTM

**Comment by ksaldana1** [comment]
Think you meant to ping @hwillson. Sneaky extra 'l'.

**Comment by rosskevin** [comment]
@gaberudy this change was working a month ago when it was merged. Commenting as such on a closed/merged PR is bound to be lost. Please file an issue or even better PR with a fix.

**Comment by rosskevin** [comment]
See https://github.com/apollographql/apollo-link/pull/911#issuecomment-455704137 for update.

**Comment by julmot** [comment]
> Commenting as such on a closed/merged PR is bound to be lost

I would theoretically agree with you, if the new issue #910 would not have been lost for over a year now.

**Pull request merged**
