### PR TITLE
fix rollup imports and sourcemap support(jest + rollup)

### LINKED ISSUE #248: zen-observable import breaks queries in apollo-client when transpiled
Hi there!

I'm working to get a new project set up with Apollo Client, Apollo Link, babel, and webpack. I use a pretty simple project template to set it up with the documented suggestions in Apollo Client. When I go to run it and send it a query, I get a runtime exception and queries cannot go through. I traced this to how the `zen-observable` package is imported.

**Intended outcome:**

Apollo Client can make a query using Apollo Link, using the following code:

```javascript
import { ApolloClient } from "apollo-client"
import { HttpLink } from "apollo-link-http"
import { InMemoryCache } from "apollo-cache-inmemory"
import { gql } from "graphql-tag"

const graphqlClient = new ApolloClient({
        link: new HttpLink(),
        cache: new InMemoryCache(),
})
graphqlClient.query({ query: gql`query { counter { count } }` })
        .then(console.log)
        .catch(console.error)
```

**Actual outcome:**

Apollo Client throws the following exception:

```
TypeError: _super.call is not a function
Stack trace:
ObservableQuery@webpack-internal:///16:56:21
QueryManager</QueryManager.prototype.watchQuery@webpack-internal:///94:404:16
QueryManager</QueryManager.prototype.query/resPromise<@webpack-internal:///94:431:20
QueryManager</QueryManager.prototype.query@webpack-internal:///94:429:26
ApolloClient</ApolloClient.prototype.query@webpack-internal:///93:102:16
@webpack-internal:///59:14:1
[59]@http://host/assets/client.js:16:1
__webpack_require__@http://host/assets/manifest.js:713:12
fn@http://host/assets/manifest.js:118:20
[49]@http://host/assets/client.js:7:18
__webpack_require__@http://host/assets/manifest.js:713:12
webpackJsonpCallback@http://host/assets/manifest.js:26:23
@http://host/assets/client.js:1:1
```

The `ObservableQuery` imports the `Observable` from the Apollo Link project, which imports it from the `zen-observable` package. When transpiled to JavaScript, the apollo-link package has this at `lib/index.js`:

```javascript
import * as Observable from 'zen-observable';
export { Observable };
```

It seems that this causes some strange case when transpiling and later subclassing this Observable, but this seems to be where the `call` method stops being available through my investigation.

**How to reproduce the issue:**

Attached is a test project which should demonstrate the issue. I assume Node.js v6 or v8 installed with Yarn. [Test Project](https://github.com/apollographql/apollo-link/files/1473237/apollo-link-test.zip)

1. Unzip and cd into the test project
2. `yarn install`
3. `yarn run start` and open http://localhost:3000/
4. You should see the error shown above in the console.

You can workaround this by changing `node_modules/apollo-link/lib/index.js:3` from:

`import * as Observable from 'zen-observable';`

to:

`import Observable from 'zen-observable';`

The problem is if you make this change in the corresponding .ts file, it causes a linting failure, and I'm not sure how best to resolve that.

There is [this issue on StackOverflow](https://stackoverflow.com/questions/47156532/apollo-client-2-with-react-couldnt-make-query) which suggests that other people are having this issue.

Thank you so much for your time, for looking at my bug report, and for the awesome work on Apollo!

### PR DESCRIPTION
**Pull request by jbaxleyiii**
Fixes #248 

cc @evans

### CODE REVIEW

**Comment by evans** [comment]
@jbaxleyiii I added sourcemap support for [jest coverage](https://github.com/kulshekhar/ts-jest#coverage) and rollup builds(wasn't picking up the tsc sourcemaps). Tested with example from #248, so should work :pray:. We should definitely think about moving to RxJs if they have addressed the bundle size issues

**Comment by evans** [comment]
apollo-link's bundle now emits `Observable = Observable && Observable.hasOwnProperty('default') ? Observable['default'] : Observable;` and the index contains `import Observable from 'zen-observable';
`, so we should be set

**Comment by littletower** [comment]
awesome! when will this be merged? :blush: thanks!

**Comment by jbaxleyiii** [comment]
@evans AMAZING

**Comment by evans** [comment]
@littletower We merged and published. Can you post in #389 if it still doesn't work with 1.2.0

**Comment by JounQin** [comment]
It breaks https://github.com/apollographql/apollo-link/issues/511, and requires 
adding `allowSyntheticDefaultImports: true` into `tsconfig.json`, is that reasonable to require specific tsconfig?

**Comment by evans** [comment]
@JounQin Good point! We shouldn't be forcing a specific `tsconfig.json`. I think the best way forward is to either switch to RxJs or write an implementation of zen-observable in typescript, since the `* as` imports break js builds and a direct import necessitates the `allowSyntheticDefaultImports`. Please take a look at #515. If you think there is a better way forward please share.

**Pull request merged**
