### PR TITLE
Fix for issue apollo-link #910

### PR DESCRIPTION
**Pull request by syndesis**
Removed type from ExecutionResult to pass linting

### CODE REVIEW

**Comment by rosskevin** [comment]
We should not untype a result, if the types has changed we should look at correcting it.

**Comment by rosskevin** [comment]
Wow! the result is now untyped so this is the correct fix.  The updated code is https://github.com/graphql/graphql-js/blob/master/src/execution/execute.js#L114-L117:

```tsx
/**
 * The result of GraphQL execution.
 *
 *   - `errors` is included when any errors occurred as a non-empty array.
 *   - `data` is the result of a successful execution of the query.
 */
export type ExecutionResult = {
  errors?: $ReadOnlyArray<GraphQLError>,
  data?: ObjMap<mixed>,
};
```

which is a step backwards and will introduce a problem code in apollo-client.  It looks like apollo-client will have to cast to `any` and then cast to a result.  

/cc @danilobuerger you might look at casting/correcting this inside apollo-client. I can't see a reason or find the commit where the generic was removed in https://github.com/graphql/graphql-js/commits/master/src/execution/execute.js but it is clearly gone now.  Since this is two steps removed from apollo-client, perhaps it is best to just cast it there?

@hwillson this is good to merge and will need a patch release to avoid breakage with `graphql` dependency.

**Comment by rosskevin** [comment]
Looks like my original PR #804 was based on `@types/graphql` - still looking - need to check definitelytyped....

**Comment by rosskevin** [comment]
Ok, looks like the code is still on DefinitelyTyped, so this should not be needed.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/graphql/execution/execute.d.ts#L43

```tsx
/**
 * The result of GraphQL execution.
 *
 *   - `errors` is included when any errors occurred as a non-empty array.
 *   - `data` is the result of a successful execution of the query.
 */
export interface ExecutionResult<TData = ExecutionResultDataDefault> {
    errors?: ReadonlyArray<GraphQLError>;
    data?: TData;
}
```

**Comment by gaberudy** [comment]
See the discussion of adding types to the data result here for DefinitelyTyped:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26763

I think not being type compatible with graphql-js is a strong negative though and caused my issue.

**Comment by syndesis** [comment]
Cancelling per updates from @rosskevin

**Pull request closed without merging**
